<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:fo="http://www.w3.org/1999/XSL/Format"
		version="1.0">

	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
	     
	     These are the common text routines for both the 'individual.xsl' 
	     and the 'index.xsl' which can be included by using
	     
	     <xsl:include href="classpath://!/common-text.xsl"/>
	     
	     Which uses a custom resolver to find the file within the classpath
	     
	     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

	<xsl:template name="front-page-attribution">
			<!--
			  Static content that goes at the base of the first page.  If this page
			  spans more than just the first page, it will appear on all pages
			  -->
			<fo:static-content flow-name="xsl-region-after">
				<fo:block font-size="10pt" font-family="Courier" line-height="15pt" margin-bottom="0pt" text-align="center" border-top="solid">
					Thoughtfully generated by the synapticloop tag library descriptor documentation generator (synapticloop-tlddoc)
				</fo:block>
				<fo:block font-size="10pt" font-family="Courier" line-height="15pt" margin-bottom="0pt" text-align="center" text-decoration="underline">
					<fo:basic-link external-destination="url('http://www.synapticloop.com/')">http://www.synapticloop.com/</fo:basic-link>
				</fo:block>
			</fo:static-content>
	</xsl:template>

	<xsl:template name="table-row-courier">
		<xsl:param name="title"/>
		<xsl:param name="value"/>
		<xsl:if test="$value != '' and $title != ''">
			<fo:table-row>
				<fo:table-cell padding="3pt">
					<fo:block font-size="10pt"
							font-family="Courier"
							line-height="15pt"
							margin-bottom="0pt"
							text-align="justify">
						<fo:inline font-weight="bold" font-family="sans-serif" padding-right="2pt"><xsl:value-of select="$title" />  </fo:inline><xsl:value-of select="$value" />
					</fo:block>
				</fo:table-cell>
			</fo:table-row>
		</xsl:if>
	</xsl:template>

	<xsl:template name="table-row-courier-large">
		<xsl:param name="title"/>
		<xsl:param name="value"/>
		<xsl:if test="$value != '' and $title != ''">
			<fo:table-row>
				<fo:table-cell padding="3pt">
					<fo:block font-size="15pt"
							font-family="Courier"
							line-height="15pt"
							margin-bottom="0pt"
							text-align="justify">
						<fo:inline font-weight="bold" font-family="sans-serif"><xsl:value-of select="$title" /></fo:inline> <xsl:value-of select="$value" />
					</fo:block>
				</fo:table-cell>
			</fo:table-row>
		</xsl:if>
	</xsl:template>

	<xsl:template name="document-heading">
		<xsl:param name="heading" />

		<fo:block font-size="28pt" 
			font-family="Courier" 
			line-height="28pt"
			margin-bottom="15pt" 
			color="black"
			text-align="center"
			padding="3pt"
			background-color="#CDCCFD"
			border-bottom-style="solid"
			border-bottom-width="10pt"
			border-color="#000000"
			id="front-page">
			<xsl:value-of select="$heading" />
		</fo:block>
	</xsl:template>

	<xsl:template name="document-sub-heading">
		<xsl:param name="heading" />
		<fo:block font-size="18pt" 
			font-family="Courier" 
			line-height="24pt"
			margin-bottom="15pt" 
			text-align="center"
			color="black"
			padding="3pt"
			border-color="#000000"
			border-bottom-style="solid"
			border-bottom-width="1pt">
			<xsl:value-of select="$heading" />
		</fo:block>
	</xsl:template>
	<!--
	  Create a page heading that also creates a link to the page using the 
	  heading as the id
	  -->
	<xsl:template name="page-heading">
		<xsl:param name="heading" />
		<fo:block font-size="18pt" font-family="Courier" line-height="24pt" margin-bottom="15pt" color="black" text-align="left" padding="3pt" border-style="solid" background-color="#CCCCFF" id="{$heading}">
			<xsl:value-of select="$heading" />
		</fo:block>
	</xsl:template>

	<xsl:template name="tag-page-heading">
		<xsl:param name="heading" />

		<fo:block>
			<fo:inline font-size="60pt"
								font-family="Courier"
								margin-bottom="30pt"
								margin-left="-15pt"
								padding="5px"
								padding-top="10pt"
								border="solid"
								border-width="1px"
								border-color="#000"
								background-color="#CDCCFD"
								id="{$heading}">
				<xsl:value-of select="$heading" />
			</fo:inline>
		</fo:block>
	</xsl:template>

	<xsl:template name="reference-heading">
		<xsl:param name="heading" />

		<fo:block font-size="18pt" font-family="serif" line-height="24pt" margin-bottom="15pt" color="black" text-align="left" padding="3pt" border-bottom-style="solid" id="{$heading}" span="all">
			<fo:inline font-style="italic"><xsl:value-of select="$heading" /></fo:inline>
		</fo:block>
	</xsl:template>

	<!-- Normal paragraph text output -->
	<xsl:template name="normal-paragraph">
		<xsl:param name="text" />
		<fo:block font-size="12pt" line-height="15pt" padding-top="7pt" margin-bottom="3pt" text-align="justify" font-family="serif">
			<xsl:value-of select="$text" />
		</fo:block>
	</xsl:template>

	<!-- Normal serif paragraph text output -->
	<xsl:template name="normal-serif-paragraph">
		<xsl:param name="text" />
		<fo:block font-size="12pt" line-height="15pt" padding-top="7pt" margin-bottom="3pt" text-align="justify" font-family="serif">
			<xsl:value-of select="$text" />
		</fo:block>
	</xsl:template>

	<!-- Padded paragraph text output -->
	<xsl:template name="padded-paragraph">
		<xsl:param name="text" />
		<fo:block font-size="12pt" line-height="15pt" margin-bottom="13pt" text-align="justify" font-family="serif">
			<xsl:value-of select="$text" />
		</fo:block>
	</xsl:template>

	<!-- Paragraph with a bold heading -->
	<xsl:template name="bold-heading-paragraph">
		<xsl:param name="heading" />
		<xsl:param name="text" />

		<fo:block font-size="10pt" font-family="serif" line-height="15pt" margin-bottom="3pt" text-align="justify">
			<fo:inline font-weight="bold"><xsl:value-of select="$heading" /></fo:inline> <xsl:value-of select="$text" />
		</fo:block>
		
	</xsl:template>
</xsl:stylesheet>